// Generated by Wrangler by running `wrangler types`

/// <reference types="@cloudflare/workers-types" />

interface Env {
	ENVIRONMENT: "development";
	LLM_MODEL: "@cf/meta/llama-3.3-70b-instruct-fp8-fast";
	LLM_MAX_TOKENS: "500";
	LLM_TEMPERATURE: "0.7";
	RAG_ENABLED: "true";
	RAG_TOP_K: "3";
	OPENWEATHER_API_KEY: string;
	POSTMARK_API_KEY: string;
	POSTMARK_FROM_EMAIL: string;
	CODE_EXECUTION_TIMEOUT: string;
	CONFIRMATION_TIMEOUT: string;
	MAX_CODE_LENGTH: string;
	AGENT: DurableObjectNamespace /* PersonalAssistant from agent-db */;
	DB: D1Database;
	VECTORIZE: VectorizeIndex;
	AI: Ai;
	TASK_WORKFLOW: Workflow;
}
